version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    network_mode : "host"
    ports:
     - 27018:27017
    # hostname: 'localhost'
    environment:
     - MONGO_INITDB_ROOT_USERNAME=root
     - MONGO_INITDB_ROOT_PASSWORD=password
    # networks:
    #  - mongo-network

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    network_mode: "host"
    #restart: always
    ports:
     - 8081:8081
    # hostname: 'localhost'
    environment:
     - ME_CONFIG_MONGODB_ADMINUSERNAME=root
     - ME_CONFIG_MONGODB_ADMINPASSWORD=password
     - ME_CONFIG_MONGODB_SERVER=mongodb
    # links:
    #  - "mongodb"
    # networks:
    #  - mongo-network

